name: "registry"
version: "0.4.1"
usage: "Integrate app-registry client to HELM"
description: |-
  This plugin provides app-registry client to Helm.
ignoreFlags: false
useTunnel: false
command: "$HELM_PLUGIN_DIR/cnr.sh"
