name: "registry"
version: "0.4.0"
usage: "Integrate CNR client to HELM"
description: |-
  This plugin provides CNR client to Helm.
ignoreFlags: false
useTunnel: false
command: "$HELM_PLUGIN_DIR/cnr.sh"
